import {
  BookOpen,
  CalendarDays,
  ClipboardCheck,
  GraduationCap,
  LayoutDashboard,
  School,
  Users,
} from "lucide-react";

export const roleCopy = {
  admin: { label: "Administrator", eyebrow: "Operations workspace" },
  teacher: { label: "Faculty workspace", eyebrow: "Teaching workspace" },
  student: { label: "Student workspace", eyebrow: "Personal overview" },
};

export const adminResources = [
  {
    key: "departments",
    label: "Departments",
    endpoint: "/admin/departments",
    create: "/admin/departments",
    update: "/admin/departments",
    remove: "/admin/departments",
    id: "dept_id",
    editFields: [
      ["dept_name", "Department name"],
      ["dept_code", "Department code"],
      ["description", "Description"],
    ],
    icon: School,
    fields: [
      ["college_id", "College ID", "number"],
      ["dept_name", "Department name"],
      ["dept_code", "Department code"],
      ["description", "Description"],
    ],
  },
  {
    key: "teachers",
    label: "Teachers",
    endpoint: "/admin/teachers",
    create: "/admin/teachers",
    update: "/admin/teachers",
    remove: "/admin/teachers",
    id: "teacher_id",
    editFields: [
      ["name", "Full name"],
      ["email", "Email", "email"],
      ["teacher_code", "Teacher code"],
      ["designation", "Designation"],
      ["experience", "Experience (years)", "number"],
      ["join_date", "Join date", "date"],
    ],
    icon: Users,
    fields: [
      ["name", "Full name"],
      ["email", "Email", "email"],
      ["password", "Initial password", "password"],
      ["teacher_code", "Teacher code"],
      ["designation", "Designation"],
      ["experience", "Experience (years)", "number"],
      ["join_date", "Join date", "date"],
    ],
  },
  {
    key: "students",
    label: "Students",
    endpoint: "/admin/students",
    create: "/admin/students",
    update: "/admin/students",
    remove: "/admin/students",
    id: "student_id",
    editFields: [
      ["name", "Full name"],
      ["email", "Email", "email"],
      ["dept_id", "Department ID", "number"],
      ["roll_no", "Roll number"],
      ["c_roll_no", "Class roll number"],
      ["year", "Year", "number"],
      ["sem", "Semester", "number"],
      ["section", "Section"],
    ],
    icon: GraduationCap,
    fields: [
      ["name", "Full name"],
      ["email", "Email", "email"],
      ["password", "Initial password", "password"],
      ["dept_id", "Department ID", "number"],
      ["roll_no", "Roll number"],
      ["c_roll_no", "Class roll number"],
      ["year", "Year", "number"],
      ["sem", "Semester", "number"],
      ["section", "Section"],
    ],
  },
  {
    key: "subjects",
    label: "Subjects",
    endpoint: "/admin/subjects",
    create: "/admin/subjects",
    update: "/admin/subjects",
    remove: "/admin/subjects",
    id: "subject_id",
    editFields: [
      ["dept_id", "Department ID", "number"],
      ["subject_name", "Subject name"],
      ["subject_code", "Subject code"],
      ["year", "Year", "number"],
      ["sem", "Semester", "number"],
    ],
    icon: BookOpen,
    fields: [
      ["dept_id", "Department ID", "number"],
      ["subject_name", "Subject name"],
      ["subject_code", "Subject code"],
      ["year", "Year", "number"],
      ["sem", "Semester", "number"],
    ],
  },
  {
    key: "subject-teachers",
    label: "Assignments",
    endpoint: "/admin/subject-teachers",
    create: "/admin/subject-teachers",
    update: "/admin/subject-teachers",
    remove: "/admin/subject-teachers",
    id: "st_id",
    editFields: [
      ["dept_id", "Department", "number"],
      ["subject_id", "Subject", "number"],
      ["teacher_id", "Teacher", "number"],
    ],
    icon: ClipboardCheck,
    fields: [
      ["dept_id", "Department", "number"],
      ["subject_id", "Subject", "number"],
      ["teacher_id", "Teacher", "number"],
    ],
  },
  {
    key: "slots",
    label: "Time slots",
    endpoint: "/admin/slots",
    create: "/admin/slots",
    update: "/admin/slots",
    remove: "/admin/slots",
    id: "slot_id",
    editFields: [
      ["start_time", "Start time", "time"],
      ["end_time", "End time", "time"],
      ["slot_name", "Slot name"],
    ],
    icon: CalendarDays,
    fields: [
      ["start_time", "Start time", "time"],
      ["end_time", "End time", "time"],
      ["slot_name", "Slot name"],
    ],
  },
  {
    key: "routines",
    label: "Routines",
    endpoint: "/admin/routines",
    create: "/admin/routines",
    icon: CalendarDays,
    fields: [
      ["dept_id", "Department", "number"],
      ["st_id", "Assignment", "number"],
      ["teacher_id", "Available teacher", "number"],
      ["slot_id", "Time slot", "number"],
      ["day", "Day"],
    ],
  },
];

export const navByRole = {
  admin: [{ key: "overview", label: "Overview", icon: LayoutDashboard }, ...adminResources],
  teacher: [
    { key: "overview", label: "Overview", icon: LayoutDashboard },
    { key: "subjects", label: "My subjects", endpoint: "/teacher/my-subjects", icon: BookOpen },
    { key: "routine", label: "My routine", endpoint: "/teacher/my-routine", icon: CalendarDays },
    { key: "attendance", label: "Attendance", endpoint: "/teacher/attendance", icon: ClipboardCheck },
    {
      key: "teacher-history",
      label: "Attendance history",
      endpoint: "/teacher/attendance/history",
      icon: CalendarDays,
    },
  ],
  student: [
    { key: "overview", label: "Overview", icon: LayoutDashboard },
    { key: "attendance", label: "My attendance", endpoint: "/student/attendance-summary", icon: ClipboardCheck },
    { key: "history", label: "History", endpoint: "/student/attendance-history", icon: CalendarDays },
    { key: "routine", label: "My routine", endpoint: "/student/my-routine", icon: CalendarDays },
  ],
};
